---
title: "RF"
author: "Ethan Aslami"
date: "2025-07-09"
output: html_document
---
# Load and Explore Data
```{r}
suppressWarnings(library(tidyverse))
library(caret)
library(randomForest)
library(janitor)
library(here)
library(quanteda)
library(quanteda.textstats)
```

# Load Data and preprocessing
```{r}

source("preprocessing_master.R")
```


## RandomForest 

```{r}

# check most frequent words
topfeatures(dfm_reviews, 20)

# Check Word Frequencies by Class
textstat_keyness(dfm_reviews, target = korean_reviews$rank_group == "High") %>% 
  head(10)

textstat_keyness(dfm_reviews, target = korean_reviews$rank_group == "Low") %>% 
  head(10)


# Word Cloud
library(quanteda.textplots)
textplot_wordcloud(dfm_group(dfm_reviews, groups = korean_reviews$rank_group), 
                   comparison = TRUE, 
                   max_words = 100, 
                   color = c("darkgreen", "red"))

# Add group labels to your DFM
docvars(dfm_reviews, "rank_group") <- korean_reviews$rank_group


X <- convert(dfm_reviews, to = "matrix")
y <- docvars(dfm_reviews, "rank_group")


set.seed(123)
library(caret)
train_index <- createDataPartition(y, p = 0.8, list = FALSE)
X_train <- X[train_index, ]
X_test  <- X[-train_index, ]
y_train <- y[train_index]
y_test  <- y[-train_index]


library(randomForest)
rf_model <- randomForest(x = X_train, y = y_train, ntree = 500, importance = TRUE)

# Predict and evaluate
pred_rf <- predict(rf_model, X_test)
confusionMatrix(pred_rf, y_test)


varImpPlot(rf_model, type = 2)

```

# More complex Model with more features 
```{r}


```